name: Java CI with Maven

on:
  push:
    branches:
      - development
      - staging
      - uat
      - main
  pull_request:
    branches:
      - development
      - staging
      - uat
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Clone SpringModels repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret for the GitHub token
      run: |
        git clone https://$GH_TOKEN@github.com/nahushr18/SpringModels.git
        cd SpringModels
        git checkout development

    - name: Build SpringModels with Maven
      run: |
        cd SpringModels
        mvn clean install

    - name: Copy JAR to SpringFrontEnd/libs
      run: |
        mkdir -p SpringFrontEnd/libs
        cp SpringModels/target/SpringModels-1.0-SNAPSHOT.jar SpringFrontEnd/libs/SpringModels-1.0-SNAPSHOT.jar

    - name: Build main project with Maven
      run: mvn -B package --file pom.xml
